// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>


[id='running-node-app_{context}']
// tag::intro[]
= Running a Node.js messaging app

The Red Hat Developer Launcher enables you to build and deploy applications on OpenShift.
In this procedure, you deploy an example Node.js application that is pre-configured to allow you enter details of fruit stock.
// end::intro[]

:launcher-url:http://launcher-launcher.apps.pwright.openshiftworkshop.com/
:openshift-url: https://master.pwright.openshiftworkshop.com/console/project/eval/overview


. Log in to the link:{launcher-url}[Red Hat Developer Launcher].

. Select the *LAUNCH YOUR PROJECT*.

. Enter a name for your application, for example `my-node-app` and select *Continue*.

. Select *Code Locally, Build and Deploy* to deploy the application on a hosted OpenShift instance. Click the blue down arrow to continue.

. Select *Messaging Work Queue* from the list of missions and *Node.js* from the list of runtimes. 
+
Choose the *Integreatly* version of Node.js. Click the blue down arrow to continue.

. Select the *Log in & Authorize Account* button and give OpenShift permissions to your GitHub account. Click the blue down arrow to continue.

. Review your configuration and select *Set Up Application* to create an OpenShift deployment.
+
NOTE: Creating this application automatically creates an OpenShift project of the same name.

. Edit the messaging-service configmap, setting the values for `MESSAGING_SERVICE_PASSWORD` and `MESSAGING_SERVICE_USER` to the values from the EnMasse binding secret:
+
----
oc edit cm messaging-service -n eval
----
. Restart the application:
+
----
oc rollout latest nodejs-messaging-work-queue-frontend -n eval
----