runtime:
  cache_dir: ./.cache/antora
site:
  title: Walkthroughs
  url: https://www.redhat.com
  start_page: integreatly::index
content:
  sources:
  - url: https://github.com/integr8ly/tutorial-web-app.git
    branches: development
    start_path: docs
ui:
  bundle:
    url: https://github.com/finp/rh-ui/raw/master/build/ui-bundle.zip
    snapshot: true

asciidoc:
  attributes:
    context: 'antora'
    location: 'remote'
    experimental: ''
    idprefix: ''
    idseparator: '-'
    linkattrs: ''
