runtime:
  cache_dir: ./.cache/antora
site:
  title: Walkthroughs
  url: https://www.redhat.com
  start_page: integreatly::steel-thread
content:
  sources:
  - url: .
    branches: HEAD
ui:
  bundle:
    url: https://github.com/finp/rh-ui/raw/master/build/ui-bundle.zip
    snapshot: true

asciidoc:
  extensions:
  - ./lib/remote-include-processor
  attributes:
    context: 'antora'
    experimental: ''
    idprefix: ''
    idseparator: '-'
    linkattrs: ''
